name: Your New Jekyll Site
markdown: redcarpet
## github-pages
## defaults
# pygments: true
# github: [Repository metadata](https://help.github.com/articles/repository-metadata-on-github-pages)
## non-overridable defaults
#safe: true
#lsi: false
#source: .
