name: that bright instrument
markdown: kramdown
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
permalink: /:year/:month/:title
## github-pages
## defaults
# pygments: true
# github: [Repository metadata](https://help.github.com/articles/repository-metadata-on-github-pages)
## non-overridable defaults
#safe: true
#lsi: false
#source: .
