name: that bright instrument
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
permalink: /:title
url: http://nicknovitski.com
repository: nicknovitski/nicknovitski.github.io
author:
  name: Nick Novitski
  email: site@nicknovitski.com
  uri: http://nicknovitski.com/about
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - '*.nix'
  - result
  - vendor
## github-pages
## defaults
# pygments: true
# github: [Repository metadata](https://help.github.com/articles/repository-metadata-on-github-pages)
## non-overridable defaults
#safe: true
#lsi: false
#source: .
