name: that bright instrument
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
permalink: /:categories/:title
url: http://nicknovitski.com
author:
  name: Nick Novitski
  email: site@nicknovitski.com
  uri: http://nicknovitski.com/about
## github-pages
## defaults
# pygments: true
# github: [Repository metadata](https://help.github.com/articles/repository-metadata-on-github-pages)
## non-overridable defaults
#safe: true
#lsi: false
#source: .
